# Generated by Django 2.1.5 on 2020-04-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap_urls',
            options={'managed': False, 'verbose_name_plural': 'roadmap_urls'},
        ),
    ]
