# Generated by Django 2.1.5 on 2019-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProgressHistorical',
            fields=[
                ('upload_id', models.CharField(blank=True, max_length=12, null=True)),
                ('current_process', models.CharField(blank=True, max_length=255, null=True)),
                ('time_start', models.DateTimeField(primary_key=True, serialize=False)),
                ('time_elapsed', models.CharField(blank=True, max_length=20, null=True)),
                ('upload_type', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'upload_progress_historical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_address', models.CharField(blank=True, max_length=255, null=True)),
                ('website_display', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'website_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('percent_loss', models.FloatField(blank=True, null=True)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteStatusT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_loss', models.FloatField(blank=True, null=True)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_status_t',
                'managed': False,
            },
        ),
    ]
