# Generated by Django 2.1.5 on 2019-06-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_uploadprogresshistorical_websiteinfo_websitestatus_websitestatust'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_loss', models.FloatField(blank=True, null=True)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_ping_result',
                'managed': False,
            },
        ),
    ]
