# Generated by Django 2.1.5 on 2020-01-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_websitepingresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_title', models.CharField(blank=True, max_length=255, null=True)),
                ('roadmap_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'roadmap_urls',
                'managed': False,
            },
        ),
    ]
