# Generated by Django 2.1.5 on 2019-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxLogEarlyaccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('log_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sandbox_log_earlyaccess',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SandboxLogLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('log_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sandbox_log_live',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadProgressCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxdate', models.DateField(blank=True, null=True)),
                ('upload_type', models.CharField(blank=True, max_length=20, null=True)),
                ('upload_id', models.CharField(blank=True, max_length=12, null=True)),
                ('count_num', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'upload_progress_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadProgressCurrent',
            fields=[
                ('current_process', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_elapsed', models.CharField(blank=True, max_length=20, null=True)),
                ('current_upload_type', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'upload_progress_current',
                'managed': False,
            },
        ),
    ]
