"""
Django settings for rekt project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from django.core.exceptions import ImproperlyConfigured
from local.dbCreds import *
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
#DEBUG = True

ALLOWED_HOSTS = ['rekt.superdataresearch.io',
                 'rekt-eb.us-east-1.elasticbeanstalk.com',
                 'rekt.superdataresearch.com',
                 'rekt-nginx.superdataresearch.com',
                 'hive.superdataresearch.io',
                 'rekt-prod.us-east-1.elasticbeanstalk.com',
                 '10.4.39.122', '127.0.0.1', '10.246.165.187',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kb',
    'ds',
    'argus',
    'process',
    'roadmaps',
    'widget_tweaks',
    'ckeditor',
    'ckeditor_uploader',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'rekt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rekt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rekt',
        'USER':rekt_u,
        'PASSWORD':rekt_p,
        'HOST':"rekt-rds.c2xidsbamodi.us-east-1.rds.amazonaws.com",
        'PORT':'3306'
    },
    'dashboard':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Dashboard',
        'USER':lab_u,
        'PASSWORD':lab_p,
        'HOST':"labrds.c2xidsbamodi.us-east-1.rds.amazonaws.com",
        #'HOST':"labrds-new.c2xidsbamodi.us-east-1.rds.amazonaws.com",
        'PORT':'3306',
        'OPTIONS': {
            'connect_timeout':1,
        }
    },
    'sandbox':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sandbox_transfer',
        'USER':lab_u,
        'PASSWORD':lab_p,
        'HOST':"labrds.c2xidsbamodi.us-east-1.rds.amazonaws.com",
        'PORT':'3306',
        'OPTIONS': {
            'connect_timeout':1,
        }
    },
    'argus':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Argus',
        'USER':lab_u,
        'PASSWORD':lab_p,
        'HOST':"labrds.c2xidsbamodi.us-east-1.rds.amazonaws.com",
        'PORT':'3306',
        'OPTIONS': {
            'connect_timeout':1,
        }
    },
    'live':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Dashboard',
        'USER':lab_u,
        'PASSWORD':lab_p,
        'HOST':"arcade-frontend-cluster.cluster-c2xidsbamodi.us-east-1.rds.amazonaws.com",
        'PORT':'3306',
        'OPTIONS': {
            'connect_timeout':1,
        }
    },
    'supreme':{
        'ENGINE': 'django.db.backends.mysql',
        'USER':lab_u,
        'PASSWORD':lab_p,
        'HOST':"supreme.c2xidsbamodi.us-east-1.rds.amazonaws.com",
        'PORT':'3306',
        'OPTIONS': {
            'connect_timeout':1,
        }
    },
    'arena':{
        'ENGINE': 'django.db.backends.mysql',
        'USER':arena_u,
        'PASSWORD':arena_p,
        'HOST':"arenards-useast-1b.c2xidsbamodi.us-east-1.rds.amazonaws.com",
        'PORT':'3306',
        'OPTIONS': {
            'connect_timeout':1,
        }
    },
    'xr':{
        'ENGINE': 'django.db.backends.mysql',
        'USER':xr_u,
        'PASSWORD':xr_p,
        'HOST':"xr-rds.c2xidsbamodi.us-east-1.rds.amazonaws.com",
        'PORT':'3306',
        'OPTIONS': {
            'connect_timeout':1,
        }
    },
    'timber':{
        'ENGINE':'django.db.backends.mysql',
        'NAME': 'arcade_logs_summary',
        'USER': timber_u,
        'PASSWORD': timber_p,
        'HOST': 'gatekeeper-timber-instance-1.c2xidsbamodi.us-east-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'connect_timeout':1,
        }
    },
    'arcade_frontend':{
        'ENGINE':'django.db.backends.mysql',
        'NAME': 'Horizon',
        'USER': frontend_u,
        'PASSWORD': frontend_p,
        'HOST': 'arcade-frontend-cluster.cluster-c2xidsbamodi.us-east-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'connect_timeout':1,
        }
    }

}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

if not DEBUG:
    STATIC_ROOT = 'static/'
else:
    STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


LOGOUT_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL = 'home'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline'],
            ['TextColor', 'BGColor'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',
             'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            #['Image'],
        ],
        'width': '100%',
    },
}

CKEDITOR_UPLOAD_PATH = os.path.join(MEDIA_ROOT, 'uploads/')

AWS_ACCESS_KEY_ID = aws_access_key_id
AWS_SECRET_ACCESS_KEY = aws_secret_access_key
AWS_STORAGE_BUCKET_NAME = 'hive-assets.superdataresearch.io'

DEFAULT_FILE_STORAGE = 'rekt.storage_backends.roadmap_storage'
AWS_DEFAULT_ACL = None
