# Generated by Django 2.1.5 on 2019-02-01 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='arcade_user',
            fields=[
                ('arcade_user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('arcade_user_firstname', models.CharField(max_length=30)),
                ('arcade_user_lastname', models.CharField(max_length=30)),
                ('arcade_user_email', models.EmailField(max_length=250)),
                ('aracde_user_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='arcade_user_log',
            fields=[
                ('arcade_user_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('arcade_user_id', models.CharField(max_length=30)),
                ('arcade_user_firstname', models.CharField(max_length=30)),
                ('arcade_user_lastname', models.CharField(max_length=30)),
                ('arcade_user_email', models.EmailField(max_length=250)),
                ('aracde_user_status', models.CharField(max_length=15)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('log_notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('orgid', models.CharField(max_length=50, unique=True)),
                ('cname', models.CharField(max_length=50)),
                ('poc_firstname', models.CharField(max_length=30)),
                ('poc_lastname', models.CharField(max_length=30)),
                ('poc_email', models.EmailField(max_length=250)),
                ('client_status', models.CharField(max_length=30)),
                ('arcade_access_status', models.CharField(max_length=30)),
                ('arcade_id', models.IntegerField()),
                ('custom_deliverables', models.CharField(max_length=10)),
                ('syndicated_reports', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='company_log',
            fields=[
                ('company_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('poc_firstname', models.CharField(max_length=30)),
                ('poc_lastname', models.CharField(max_length=30)),
                ('poc_email', models.EmailField(max_length=250)),
                ('client_status', models.CharField(max_length=30)),
                ('arcade_access_status', models.CharField(max_length=30)),
                ('arcade_id', models.IntegerField()),
                ('custom_deliverables', models.CharField(max_length=10)),
                ('syndicated_reports', models.CharField(max_length=10)),
                ('ftp_access', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('log_notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='interaction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('dates_of_last_contact', models.DateField()),
                ('notes', models.TextField(max_length=4000)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='ds.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='interaction_log',
            fields=[
                ('interaction_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_id', models.IntegerField()),
                ('dates_of_last_contact', models.DateField()),
                ('notes', models.TextField(max_length=4000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('log_notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orgid',
            fields=[
                ('orgid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='subscription_history',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_start', models.DateField()),
                ('subscription_end', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='ds.company')),
            ],
        ),
        migrations.CreateModel(
            name='subscription_history_log',
            fields=[
                ('sub_id_log', models.AutoField(primary_key=True, serialize=False)),
                ('sub_id', models.IntegerField()),
                ('subscription_start', models.DateField()),
                ('subscription_end', models.DateField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('log_notes', models.CharField(max_length=100)),
                ('orgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_his_log', to='ds.orgid')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_his_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interaction_log',
            name='orgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_log', to='ds.orgid'),
        ),
        migrations.AddField(
            model_name='interaction_log',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction_log',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_log_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company_log',
            name='orgid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_log', to='ds.orgid'),
        ),
        migrations.AddField(
            model_name='company_log',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arcade_user_log',
            name='orgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aruser_log', to='ds.orgid'),
        ),
        migrations.AddField(
            model_name='arcade_user_log',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aruser_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arcade_user',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcade_user', to='ds.company'),
        ),
    ]
