# Generated by Django 2.1.5 on 2019-09-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0002_orgid_orgid_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='subscription_history',
            options={'verbose_name_plural': 'subscription_histories'},
        ),
    ]
