# Generated by Django 2.1.5 on 2019-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0005_auto_20190911_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcade_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
