# Generated by Django 2.1.5 on 2020-02-10 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ds', '0010_auto_20200206_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('steam_id', models.CharField(blank=True, max_length=255)),
                ('twitter_id', models.CharField(blank=True, max_length=255)),
                ('epic_id', models.CharField(blank=True, max_length=255)),
                ('switch_id', models.CharField(blank=True, max_length=255)),
                ('blizz_id', models.CharField(blank=True, max_length=255)),
                ('playstation_id', models.CharField(blank=True, max_length=255)),
                ('instagram_id', models.CharField(blank=True, max_length=255)),
                ('discord_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='profile_photo',
            fields=[
                ('photo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('upload_photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ds.profile_photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
