# Generated by Django 2.1.5 on 2020-02-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0011_auto_20200210_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='photo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
