# Generated by Django 2.1.5 on 2020-02-10 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ds', '0012_auto_20200210_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_photo',
            name='updated_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='UserPhoto', to=settings.AUTH_USER_MODEL),
        ),
    ]
