# Generated by Django 2.1.5 on 2020-02-10 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ds', '0017_auto_20200210_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_photo', models.FileField(upload_to='')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPhoto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ds.profile_photo'),
        ),
    ]
