# Generated by Django 2.1.5 on 2020-02-12 21:02

from django.db import migrations, models
import rekt.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0022_auto_20200211_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_photo',
            name='upload_photo',
            field=models.ImageField(storage=rekt.storage_backends.photo_storage(), upload_to=''),
        ),
    ]
