# Generated by Django 2.1.5 on 2020-02-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0027_auto_20200224_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contact',
            new_name='contract',
        ),
    ]
