# Generated by Django 2.1.5 on 2020-03-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0033_xr_sub_history_log_xr_subscription_history_xr_user_xr_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='xr_user',
            name='xr_user_status',
            field=models.CharField(default='INACTIVE', max_length=15),
        ),
    ]
