# Generated by Django 2.1.5 on 2020-03-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0034_xr_user_xr_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xr_user',
            old_name='comopany_id',
            new_name='company_id',
        ),
    ]
