# Generated by Django 2.1.5 on 2020-03-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0037_company_xr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_log',
            name='xr_status',
            field=models.CharField(default='INACTIVE', max_length=30),
        ),
    ]
