# Generated by Django 2.1.5 on 2019-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleLevelRegionVsSubregionF2PConsoleMau',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_region_mau', models.IntegerField(blank=True, db_column='Total Region MAU', null=True)),
                ('sub_region_mau', models.IntegerField(blank=True, db_column='Sub Region MAU', null=True)),
                ('mau_difference_percentage', models.DecimalField(blank=True, db_column='MAU Difference Percentage', decimal_places=5, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'title_level_region_vs_subregion_f2p_console_mau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelRegionVsSubregionF2PConsoleRevenue',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_region_revenue', models.FloatField(blank=True, db_column='Total Region Revenue', null=True)),
                ('sub_region_revenue', models.FloatField(blank=True, db_column='Sub Region Revenue', null=True)),
                ('revenue_difference_percentage', models.FloatField(blank=True, db_column='Revenue Difference Percentage', null=True)),
            ],
            options={
                'db_table': 'title_level_region_vs_subregion_f2p_console_revenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelRegionVsSubregionF2PPcMau',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_region_mau', models.IntegerField(blank=True, db_column='Total Region MAU', null=True)),
                ('sub_region_mau', models.IntegerField(blank=True, db_column='Sub Region MAU', null=True)),
                ('mau_difference_percentage', models.DecimalField(blank=True, db_column='MAU Difference Percentage', decimal_places=5, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'title_level_region_vs_subregion_f2p_pc_mau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelRegionVsSubregionF2PPcRevenue',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_region_revenue', models.FloatField(blank=True, db_column='Total Region Revenue', null=True)),
                ('sub_region_revenue', models.FloatField(blank=True, db_column='Sub Region Revenue', null=True)),
                ('revenue_difference_percentage', models.FloatField(blank=True, db_column='Revenue Difference Percentage', null=True)),
            ],
            options={
                'db_table': 'title_level_region_vs_subregion_f2p_pc_revenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelWwVsRegionsF2PConsoleMau',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('worldwide_mau', models.BigIntegerField(blank=True, db_column='Worldwide MAU', null=True)),
                ('regions_mau', models.DecimalField(blank=True, db_column='Regions MAU', decimal_places=0, max_digits=41, null=True)),
                ('mau_difference_percentage', models.DecimalField(blank=True, db_column='MAU Difference Percentage', decimal_places=5, max_digits=50, null=True)),
            ],
            options={
                'db_table': 'title_level_ww_vs_regions_f2p_console_mau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelWwVsRegionsF2PConsoleRevenue',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('worldwide_revenue', models.FloatField(blank=True, db_column='Worldwide Revenue', null=True)),
                ('regions_revenue', models.FloatField(blank=True, db_column='Regions Revenue', null=True)),
                ('revenue_difference_percentage', models.FloatField(blank=True, db_column='Revenue Difference Percentage', null=True)),
            ],
            options={
                'db_table': 'title_level_ww_vs_regions_f2p_console_revenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelWwVsRegionsF2PPcMau',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('worldwide_mau', models.BigIntegerField(blank=True, db_column='Worldwide MAU', null=True)),
                ('regions_mau', models.DecimalField(blank=True, db_column='Regions MAU', decimal_places=0, max_digits=41, null=True)),
                ('mau_difference_percentage', models.DecimalField(blank=True, db_column='MAU Difference Percentage', decimal_places=5, max_digits=50, null=True)),
            ],
            options={
                'db_table': 'title_level_ww_vs_regions_f2p_pc_mau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelWwVsRegionsF2PPcRevenue',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('worldwide_revenue', models.FloatField(blank=True, db_column='Worldwide Revenue', null=True)),
                ('regions_revenue', models.FloatField(blank=True, db_column='Regions Revenue', null=True)),
                ('revenue_difference_percentage', models.FloatField(blank=True, db_column='Revenue Difference Percentage', null=True)),
            ],
            options={
                'db_table': 'title_level_ww_vs_regions_f2p_pc_revenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelWwVsRegionsP2PPcMau',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('worldwide_mau', models.BigIntegerField(blank=True, db_column='Worldwide MAU', null=True)),
                ('regions_mau', models.DecimalField(blank=True, db_column='Regions MAU', decimal_places=0, max_digits=41, null=True)),
                ('mau_difference_percentage', models.DecimalField(blank=True, db_column='MAU Difference Percentage', decimal_places=5, max_digits=50, null=True)),
            ],
            options={
                'db_table': 'title_level_ww_vs_regions_p2p_pc_mau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelWwVsRegionsP2PPcRevenue',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('worldwide_revenue', models.FloatField(blank=True, db_column='Worldwide Revenue', null=True)),
                ('regions_revenue', models.FloatField(blank=True, db_column='Regions Revenue', null=True)),
                ('revenue_difference_percentage', models.FloatField(blank=True, db_column='Revenue Difference Percentage', null=True)),
            ],
            options={
                'db_table': 'title_level_ww_vs_regions_p2p_pc_revenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelWwVsRegionsPremiumConsoleMau',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('worldwide_mau', models.BigIntegerField(blank=True, db_column='Worldwide MAU', null=True)),
                ('regions_mau', models.DecimalField(blank=True, db_column='Regions MAU', decimal_places=0, max_digits=41, null=True)),
                ('mau_difference_percentage', models.DecimalField(blank=True, db_column='MAU Difference Percentage', decimal_places=5, max_digits=50, null=True)),
            ],
            options={
                'db_table': 'title_level_ww_vs_regions_premium_console_mau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelWwVsRegionsPremiumConsoleRevenue',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, primary_key=True, serialize=False)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('worldwide_revenue', models.FloatField(blank=True, db_column='Worldwide Revenue', null=True)),
                ('regions_revenue', models.FloatField(blank=True, db_column='Regions Revenue', null=True)),
                ('revenue_difference_percentage', models.FloatField(blank=True, db_column='Revenue Difference Percentage', null=True)),
            ],
            options={
                'db_table': 'title_level_ww_vs_regions_premium_console_revenue',
                'managed': False,
            },
        ),
    ]
