# Generated by Django 2.1.5 on 2020-01-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0002_titlelevelregionvssubregionf2pconsolemau_titlelevelregionvssubregionf2pconsolerevenue_titlelevelregi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighArpmauTitleLevel',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, null=True)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('region', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('arpmau', models.FloatField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'high_arpmau_title_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighConversionRateMarketLevel',
            fields=[
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FloatField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'high_conversion_rate_market_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighConversionRateMarketLevelGenre',
            fields=[
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FloatField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'high_conversion_rate_market_level_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighConversionRateMarketLevelPlatform',
            fields=[
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FloatField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'high_conversion_rate_market_level_platform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighConversionRateTitleLevel',
            fields=[
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.FloatField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'high_conversion_rate_title_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighIngameArppuMarketLevel',
            fields=[
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ingame_arppu', models.FloatField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'high_ingame_arppu_market_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighIngameArppuMarketLevelGenre',
            fields=[
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ingame_arppu', models.FloatField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'high_ingame_arppu_market_level_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighIngameArppuMarketLevelPlatform',
            fields=[
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ingame_arppu', models.FloatField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'high_ingame_arppu_market_level_platform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighIngameArppuTitleLevel',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, null=True)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('region', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ingame_arppu', models.FloatField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'high_ingame_arppu_title_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleLevelIngameRevenueAggregate',
            fields=[
                ('title', models.CharField(blank=True, max_length=191, null=True)),
                ('segment', models.CharField(blank=True, max_length=191, null=True)),
                ('region', models.CharField(blank=True, max_length=191, null=True)),
                ('platform', models.CharField(blank=True, max_length=191, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('digital_micro_revenue', models.FloatField(blank=True, null=True)),
                ('digital_subscription_revenue', models.FloatField(blank=True, null=True)),
                ('digital_season_pass_revenue', models.FloatField(blank=True, null=True)),
                ('digital_dlc_revenue', models.FloatField(blank=True, null=True)),
                ('digital_micro_ac_revenue', models.FloatField(blank=True, null=True)),
                ('revenue_addup', models.FloatField(blank=True, primary_key=True, serialize=False)),
                ('digital_ingame_revenue', models.FloatField(blank=True, null=True)),
                ('revenue_difference_percentage', models.FloatField(blank=True, db_column='Revenue Difference Percentage', null=True)),
            ],
            options={
                'db_table': 'title_level_ingame_revenue_aggregate',
                'managed': False,
            },
        ),
    ]
