# Generated by Django 2.1.5 on 2020-08-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argus', '0003_higharpmautitlelevel_highconversionratemarketlevel_highconversionratemarketlevelgenre_highconversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duplicaterowcheckmarketlevel',
            options={'managed': False, 'verbose_name': 'Market Level'},
        ),
        migrations.AlterModelOptions(
            name='duplicaterowcheckmarketlevelgenre',
            options={'managed': False, 'verbose_name': 'Market Level Genre'},
        ),
        migrations.AlterModelOptions(
            name='duplicaterowcheckmarketlevelplatform',
            options={'managed': False, 'verbose_name': 'Market Level Platform'},
        ),
        migrations.AlterModelOptions(
            name='duplicaterowchecktitlelevel',
            options={'managed': False, 'verbose_name': 'Title Level'},
        ),
        migrations.AlterModelOptions(
            name='higharpmautitlelevel',
            options={'managed': False, 'verbose_name': 'Title Level'},
        ),
        migrations.AlterModelOptions(
            name='highconversionratemarketlevel',
            options={'managed': False, 'verbose_name': 'Market Level'},
        ),
        migrations.AlterModelOptions(
            name='highconversionratemarketlevelgenre',
            options={'managed': False, 'verbose_name': 'Market Level Genre'},
        ),
        migrations.AlterModelOptions(
            name='highconversionratemarketlevelplatform',
            options={'managed': False, 'verbose_name': 'Market Level Platform'},
        ),
        migrations.AlterModelOptions(
            name='highconversionratetitlelevel',
            options={'managed': False, 'verbose_name': 'Title Level'},
        ),
        migrations.AlterModelOptions(
            name='highingamearppumarketlevel',
            options={'managed': False, 'verbose_name': 'Market Level'},
        ),
        migrations.AlterModelOptions(
            name='highingamearppumarketlevelgenre',
            options={'managed': False, 'verbose_name': 'Market Level Genre'},
        ),
        migrations.AlterModelOptions(
            name='highingamearppumarketlevelplatform',
            options={'managed': False, 'verbose_name': 'Market Level Platform'},
        ),
        migrations.AlterModelOptions(
            name='highingamearpputitlelevel',
            options={'managed': False, 'verbose_name': 'Title Level'},
        ),
        migrations.AlterModelOptions(
            name='negativecheckmarketlevel',
            options={'managed': False, 'verbose_name': 'Market Level'},
        ),
        migrations.AlterModelOptions(
            name='negativecheckmarketlevelgenre',
            options={'managed': False, 'verbose_name': 'Market Level Genre'},
        ),
        migrations.AlterModelOptions(
            name='negativecheckmarketlevelplatform',
            options={'managed': False, 'verbose_name': 'Market Level Platform'},
        ),
        migrations.AlterModelOptions(
            name='negativechecktitlelevel',
            options={'managed': False, 'verbose_name': 'Title Level'},
        ),
        migrations.AlterModelOptions(
            name='stringcheckdevelopernameunification',
            options={'managed': False, 'verbose_name': 'Developer Name Unification'},
        ),
        migrations.AlterModelOptions(
            name='stringcheckpublishernameunification',
            options={'managed': False, 'verbose_name': 'Publisher Name Unification'},
        ),
        migrations.AlterModelOptions(
            name='stringchecktitlecasesensitivity',
            options={'managed': False, 'verbose_name': 'Title Case Sensitivity'},
        ),
        migrations.AlterModelOptions(
            name='stringcheckwhitespace',
            options={'managed': False, 'verbose_name': 'Whitespace'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelconversioningame',
            options={'managed': False, 'verbose_name': 'Conversion Ingame'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelconversionmicro',
            options={'managed': False, 'verbose_name': 'Conversion Micro'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelingamerevenueaggregate',
            options={'managed': False, 'verbose_name': 'In-Game Spending'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelmauvslifetimedownloadsexcess',
            options={'managed': False, 'verbose_name': 'MAU vs Lifetime Downloads Excess'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformf2pconsolemau',
            options={'managed': False, 'verbose_name': 'F2P Console MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformf2pconsolerevenue',
            options={'managed': False, 'verbose_name': 'F2P Console Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformf2ppcmau',
            options={'managed': False, 'verbose_name': 'F2P PC MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformf2ppcrevenue',
            options={'managed': False, 'verbose_name': 'F2P PC Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformmobilemau',
            options={'managed': False, 'verbose_name': 'Mobile MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformmobilerevenue',
            options={'managed': False, 'verbose_name': 'Mobile Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformp2ppcmau',
            options={'managed': False, 'verbose_name': 'P2P PC MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformp2ppcrevenue',
            options={'managed': False, 'verbose_name': 'P2P PC Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformpremiumconsolemau',
            options={'managed': False, 'verbose_name': 'Premium Console MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformpremiumconsolerevenue',
            options={'managed': False, 'verbose_name': 'Premium Console Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformpremiumpcmau',
            options={'managed': False, 'verbose_name': 'Premium PC MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelplatformvssubplatformpremiumpcrevenue',
            options={'managed': False, 'verbose_name': 'Premium PC Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelregionvssubregionf2pconsolemau',
            options={'managed': False, 'verbose_name': 'F2P Console MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelregionvssubregionf2pconsolerevenue',
            options={'managed': False, 'verbose_name': 'F2P Console Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelregionvssubregionf2ppcmau',
            options={'managed': False, 'verbose_name': 'F2P PC MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelregionvssubregionf2ppcrevenue',
            options={'managed': False, 'verbose_name': 'F2P PC Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelwwvsregionsf2pconsolemau',
            options={'managed': False, 'verbose_name': 'F2P Console MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelwwvsregionsf2pconsolerevenue',
            options={'managed': False, 'verbose_name': 'F2P Console Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelwwvsregionsf2ppcmau',
            options={'managed': False, 'verbose_name': 'F2P PC MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelwwvsregionsf2ppcrevenue',
            options={'managed': False, 'verbose_name': 'F2P PC Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelwwvsregionsp2ppcmau',
            options={'managed': False, 'verbose_name': 'P2P PC MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelwwvsregionsp2ppcrevenue',
            options={'managed': False, 'verbose_name': 'P2P PC Revenue'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelwwvsregionspremiumconsolemau',
            options={'managed': False, 'verbose_name': 'Premium Console MAU'},
        ),
        migrations.AlterModelOptions(
            name='titlelevelwwvsregionspremiumconsolerevenue',
            options={'managed': False, 'verbose_name': 'Premium Console Revenue'},
        ),
    ]
