# Generated by Django 2.1.5 on 2019-02-05 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_auto_20190201_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='kb.category'),
        ),
    ]
