# Generated by Django 2.1.5 on 2019-09-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0005_auto_20190709_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('roadmap', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
