# Generated by Django 2.1.5 on 2019-09-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_auto_20190904_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
