# Generated by Django 2.1.5 on 2019-09-05 14:42

from django.db import migrations, models
import kb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_auto_20190904_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='title',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='late_updated',
            field=models.DateTimeField(default=kb.models.est),
        ),
    ]
