# Generated by Django 2.1.5 on 2019-10-23 21:10

from django.db import migrations, models
import kb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_auto_20190905_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=kb.models.est),
        ),
        migrations.AlterField(
            model_name='faq',
            name='last_updated',
            field=models.DateTimeField(default=kb.models.est),
        ),
    ]
