# Generated by Django 2.1.5 on 2020-01-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0009_auto_20191023_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='roadmap',
        ),
    ]
