# Generated by Django 2.1.5 on 2019-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0003_auto_20190904_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcade_user',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='arcade_user',
            name='arcade_user_id',
            field=models.CharField(max_length=30),
        ),
    ]
