# Generated by Django 2.1.5 on 2019-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0004_auto_20190911_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcade_user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
