# Generated by Django 2.1.5 on 2019-10-11 17:22

from django.db import migrations, models
import ds.models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0006_auto_20190911_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportMasterList',
            fields=[
                ('subscription_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('org_id', models.CharField(max_length=255)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('export_boolean', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'export_master_list',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='company_log',
            name='time',
            field=models.DateTimeField(default=ds.models.est),
        ),
    ]
