# Generated by Django 2.1.5 on 2019-10-23 21:10

from django.db import migrations, models
import ds.models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0007_auto_20191011_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcade_user_log',
            name='time',
            field=models.DateTimeField(default=ds.models.est),
        ),
        migrations.AlterField(
            model_name='interaction_log',
            name='time',
            field=models.DateTimeField(default=ds.models.est),
        ),
        migrations.AlterField(
            model_name='subscription_history_log',
            name='time',
            field=models.DateTimeField(default=ds.models.est),
        ),
    ]
