# Generated by Django 2.1.5 on 2020-02-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0009_activearcadesubscriptions_arcadesubscriptionsrekt'),
    ]

    operations = [
        migrations.CreateModel(
            name='label',
            fields=[
                ('label_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_lable',
            field=models.ManyToManyField(to='ds.label'),
        ),
    ]
