# Generated by Django 2.1.5 on 2020-02-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0016_auto_20200210_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.DeleteModel(
            name='profile_photo',
        ),
    ]
