# Generated by Django 2.1.5 on 2020-02-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0028_auto_20200224_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_log',
            name='contract',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company_log',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company_log',
            name='arcade_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='company_log',
            name='poc_email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='company_log',
            name='poc_firstname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='company_log',
            name='poc_lastname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
