# Generated by Django 2.1.5 on 2020-02-24 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0029_auto_20200224_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_lable',
        ),
        migrations.AddField(
            model_name='company',
            name='company_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_labeled', to='ds.label'),
        ),
    ]
