# Generated by Django 2.1.5 on 2020-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0031_auto_20200225_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_log',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
