# Generated by Django 2.1.5 on 2020-03-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0035_auto_20200305_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='blizz_id',
            new_name='blizzard_id',
        ),
    ]
