# Generated by Django 2.1.5 on 2020-03-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0038_company_log_xr_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xr_user',
            name='xr_user_id',
        ),
        migrations.RemoveField(
            model_name='xr_user_log',
            name='xr_user_id',
        ),
    ]
