# Generated by Django 2.1.5 on 2020-03-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0039_auto_20200316_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='riot_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
