# Generated by Django 2.1.5 on 2020-08-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0040_profile_riot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('time_spent', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'page_summary',
                'managed': False,
            },
        ),
    ]
